### ISSUE TITLE
Conflicts with shared-resources

### ISSUE THREAD

**Issue by adamretter** [eXist-db/dashboard#61]
Both the Dashboard and Shared Resources apps ship with the Templating module. Unfortunately they both ship with different versions, and try and use the same namespace.

`$EXIST_HOME/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql`:
```xquery
xquery version "3.0";

(:~
 : HTML templating module
 : 
 : @version 2.1
 : @author Wolfgang Meier
 : @contributor Adam retter
:)
module namespace templates="http://exist-db.org/xquery/templates";

...
```

`$EXIST_HOME/webapp/WEB-INF/data/expathrepo/dashboard-0.4.7/modules/templates.xql`:
```xquery
xquery version "3.0";

module namespace templates="http://exist-db.org/xquery/templates";

(:~
 : HTML templating module
 : 
 : @version 2.0
 : @author Wolfgang Meier
:)

...
```

Either the Dashboard should rely on the Shared Resources, or Templating should be moved into its own library module which Dashboard then relies on.

**Comment by duncdrum** [comment]
I thought dashboard is to be deprecated? I vote independent templating library module, but that would probably break all eXide generated apps … something about omlettes

**Comment by joewiz** [comment]
Does this actually lead to a conflict, i.e., some tangible error? Or is this just a confusing situation? If you use have both installed, and you import without specifying the location, you'll always get the one from shared-resources, since it's in that app's content directory. If you want the one from dashboard, you'd have to specify its location. So I don't see how there could be a conflict, per se. That said, it would make sense to pull the one from dashboard and have it rely on the one in shared-resources.

**Comment by adamretter** [comment]
@joewiz You might be right there. I had the feeling that I could not guarantee which one would be used.

**Comment by joewiz** [comment]
@adamretter Not an issue in dashboard 2.0.
